[2023-11-03T13:20:12.651+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movies-etl-dag.write_to_es scheduled__2023-11-03T13:19:03.703142+00:00 [queued]>
[2023-11-03T13:20:12.667+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movies-etl-dag.write_to_es scheduled__2023-11-03T13:19:03.703142+00:00 [queued]>
[2023-11-03T13:20:12.668+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-11-03T13:20:12.695+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): write_to_es> on 2023-11-03 13:19:03.703142+00:00
[2023-11-03T13:20:12.704+0000] {standard_task_runner.py:57} INFO - Started process 2762 to run task
[2023-11-03T13:20:12.710+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'movies-etl-dag', 'write_to_es', 'scheduled__2023-11-03T13:19:03.703142+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/movie_pg_es.py', '--cfg-path', '/tmp/tmp6ot8golm']
[2023-11-03T13:20:12.717+0000] {standard_task_runner.py:85} INFO - Job 93: Subtask write_to_es
[2023-11-03T13:20:13.037+0000] {task_command.py:415} INFO - Running <TaskInstance: movies-etl-dag.write_to_es scheduled__2023-11-03T13:19:03.703142+00:00 [running]> on host e468bf2dfd15
[2023-11-03T13:20:13.307+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='movies-etl-dag' AIRFLOW_CTX_TASK_ID='write_to_es' AIRFLOW_CTX_EXECUTION_DATE='2023-11-03T13:19:03.703142+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-03T13:19:03.703142+00:00'
[2023-11-03T13:20:13.365+0000] {movie_pg_es.py:118} INFO - [FilmWorkES(id='37c6cd37-1222-4470-9221-3170367d134b', title='Star Trek III: The Search for Spock', type='movie', rating=6.7, created_at=datetime.datetime(2021, 6, 16, 20, 14, 9, 223080, tzinfo=TzInfo(UTC)), updated_at=datetime.datetime(2021, 6, 16, 20, 14, 9, 223097, tzinfo=TzInfo(UTC)), genre='Action, Adventure, Sci-Fi', actors_names=['Leonard Nimoy', 'James Doohan', 'DeForest Kelley', 'William Shatner'], actors_ids=['5a3d0299-2df2-4070-9fda-65ff4dfa863c', '807ce9c3-6294-485c-803a-1975066f239f', '836bb95b-6db8-4418-a110-f41663b1c025', '9758b894-57d7-465d-b657-c5803dd5b7f7'], writers_names=['Harve Bennett', 'Gene Roddenberry'], writers_ids=['58411ec0-c40a-43da-95e3-0adc74b7e7f6', '6960e2ca-889f-41f5-b728-1e7313e54d6c'], directors_names=['Leonard Nimoy'], directors_ids=['5a3d0299-2df2-4070-9fda-65ff4dfa863c'], description="In the wake of Spock's ultimate deed of sacrifice, Admiral Kirk and the Enterprise crew return to Earth for some essential repairs to their ship. When they arrive at Spacedock, they are shocked to discover that the Enterprise is to be decommissioned. Even worse, Dr. McCoy begins acting strangely and Scotty has been reassigned to another ship. Kirk is forced to steal back the Enterprise and head across space to the Genesis Planet to save Spock and bring him to Vulcan. Unknown to them, the Klingons are planning to steal the secrets of the Genesis Device for their own deadly purpose."), FilmWorkES(id='50d842be-bcda-401e-90de-b06929611ce0', title='Star Trek: Nemesis', type='movie', rating=6.4, created_at=datetime.datetime(2021, 6, 16, 20, 14, 9, 223132, tzinfo=TzInfo(UTC)), updated_at=datetime.datetime(2021, 6, 16, 20, 14, 9, 223149, tzinfo=TzInfo(UTC)), genre='Action, Adventure, Sci-Fi, Thriller', actors_names=['Patrick Stewart', 'Jonathan Frakes', 'Brent Spiner', 'LeVar Burton'], actors_ids=['57a471b1-09dc-48fd-ba8a-1211015a0110', '5bddea2c-8609-499a-a444-77e0142743c0', '972c86a5-16f4-432b-b9b3-54965291ddb0', 'fc9f27d2-aaee-46e6-b263-40ec8d2dd355'], writers_names=['John Logan', 'Gene Roddenberry', 'Rick Berman', 'Brent Spiner'], writers_ids=['1f6ad693-a134-44f1-a0a6-71e4c0dec31a', '6960e2ca-889f-41f5-b728-1e7313e54d6c', '88a99b4d-4d06-4754-b06c-93217cf53244', '972c86a5-16f4-432b-b9b3-54965291ddb0'], directors_names=['Stuart Baird'], directors_ids=['a37e91d0-3c82-43f3-8517-68699ee134d6'], description='After a joyous wedding between William Riker and Deanna Troi, Captain Picard and the Enterprise crew stumble upon a mysterious signal which results in it being a prototype android who is the twin to Data. Then the Enterprise is invited to Romulus to negotiate peace with the Romulans by their new Praetor named Shinzon. However, Shinzon is revealed to be a clone of Picard who was raised on Remus, a slave planet to the Romulans. Later on, Picard discovers that this peace treaty was nothing more than a set-up due to the fact that Shinzon needs Picard in order to survive. But little do the Enterprise crew know that Shinzon also plans to do away with the Federation by unleashing a weapon that could destroy a whole planet.')]
[2023-11-03T13:20:13.365+0000] {movie_pg_es.py:119} INFO - Processing 2 movie:
[2023-11-03T13:20:13.656+0000] {_transport.py:336} INFO - PUT http://movies_es_db:9200/_bulk [status:400 duration:0.290s]
[2023-11-03T13:20:13.657+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/movie_pg_es.py", line 126, in write_to_es
    helpers.bulk(es_conn, actions)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 291, in _process_bulk_chunk_error
    raise error
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 339, in _process_bulk_chunk
    resp = client.bulk(*args, operations=bulk_actions, **kwargs)  # type: ignore[arg-type]
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
    return api(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py", line 704, in bulk
    return self.perform_request(  # type: ignore[return-value]
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/_base.py", line 320, in perform_request
    raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
elasticsearch.BadRequestError: BadRequestError(400, 'action_request_validation_exception', 'Validation Failed: 1: index is missing;2: index is missing;')
[2023-11-03T13:20:13.713+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=movies-etl-dag, task_id=write_to_es, execution_date=20231103T131903, start_date=20231103T132012, end_date=20231103T132013
[2023-11-03T13:20:13.732+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 93 for task write_to_es (BadRequestError(400, 'action_request_validation_exception', 'Validation Failed: 1: index is missing;2: index is missing;'); 2762)
[2023-11-03T13:20:13.764+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-03T13:20:13.858+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
