[2023-11-03T13:28:09.158+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movies-etl-dag.write_to_es scheduled__2023-11-03T13:26:55.272877+00:00 [queued]>
[2023-11-03T13:28:09.170+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movies-etl-dag.write_to_es scheduled__2023-11-03T13:26:55.272877+00:00 [queued]>
[2023-11-03T13:28:09.171+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-11-03T13:28:09.190+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): write_to_es> on 2023-11-03 13:26:55.272877+00:00
[2023-11-03T13:28:09.195+0000] {standard_task_runner.py:57} INFO - Started process 2949 to run task
[2023-11-03T13:28:09.200+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'movies-etl-dag', 'write_to_es', 'scheduled__2023-11-03T13:26:55.272877+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/movie_pg_es.py', '--cfg-path', '/tmp/tmpay2k30rw']
[2023-11-03T13:28:09.204+0000] {standard_task_runner.py:85} INFO - Job 115: Subtask write_to_es
[2023-11-03T13:28:09.448+0000] {task_command.py:415} INFO - Running <TaskInstance: movies-etl-dag.write_to_es scheduled__2023-11-03T13:26:55.272877+00:00 [running]> on host e468bf2dfd15
[2023-11-03T13:28:09.854+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='movies-etl-dag' AIRFLOW_CTX_TASK_ID='write_to_es' AIRFLOW_CTX_EXECUTION_DATE='2023-11-03T13:26:55.272877+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-03T13:26:55.272877+00:00'
[2023-11-03T13:28:09.918+0000] {movie_pg_es.py:118} INFO - [FilmWorkES(id='511b8ae8-f59d-450e-b9a2-22aabba2693b', title='Star Trek VI: The Undiscovered Country', type='movie', rating=7.2, created_at=datetime.datetime(2021, 6, 16, 20, 14, 9, 223292, tzinfo=TzInfo(UTC)), updated_at=datetime.datetime(2021, 6, 16, 20, 14, 9, 223308, tzinfo=TzInfo(UTC)), genre='Action, Adventure, Sci-Fi, Thriller', actors_names=['Leonard Nimoy', 'James Doohan', 'DeForest Kelley', 'William Shatner'], actors_ids=['5a3d0299-2df2-4070-9fda-65ff4dfa863c', '807ce9c3-6294-485c-803a-1975066f239f', '836bb95b-6db8-4418-a110-f41663b1c025', '9758b894-57d7-465d-b657-c5803dd5b7f7'], writers_names=['Denny Martin Flinn', 'Lawrence Konner', 'Leonard Nimoy', 'Gene Roddenberry', 'Mark Rosenthal', 'Nicholas Meyer'], writers_ids=['1749841f-0569-49bb-96ce-3f9dd51b42e2', '59674337-e77d-422b-967c-aa01017af7c3', '5a3d0299-2df2-4070-9fda-65ff4dfa863c', '6960e2ca-889f-41f5-b728-1e7313e54d6c', 'b5fa51d6-4753-4b64-819c-2de16af5c057', 'c883c2c6-d7a4-4001-8084-e2851904e91a'], directors_names=['Nicholas Meyer'], directors_ids=['c883c2c6-d7a4-4001-8084-e2851904e91a'], description="After an explosion on their moon, the Klingons have an estimated 50 years before their ozone layer is completely depleted, and they all die. They have only one choice - to make peace with the Federation, which will mean an end to 70 years of conflict. Captain James T. Kirk and crew are called upon to help in the negotiations because of their experience with the Klingons. Peace talks don't quite proceed, and Kirk and McCoy are convicted of assassinating the Klingon High Chancellor, and imprisoned on Rura Penthe, a snowy hard-labor prison camp. Will they manage to escape? And will there ever be peace with the Klingons?"), FilmWorkES(id='de5347cf-a70d-430f-8005-786326e28794', title='Star Trek: Voyager', type='movie', rating=7.8, created_at=datetime.datetime(2021, 6, 16, 20, 14, 9, 223343, tzinfo=TzInfo(UTC)), updated_at=datetime.datetime(2021, 6, 16, 20, 14, 9, 223360, tzinfo=TzInfo(UTC)), genre='Action, Adventure, Sci-Fi', actors_names=['Kate Mulgrew', 'Robert Beltran', 'Robert Duncan McNeill', 'Roxann Dawson'], actors_ids=['7f100195-5faf-4746-8a2b-df2a3e57cc8b', '83e09e52-4a63-49f9-8c34-3d09774f7509', 'c05da398-b37e-4993-8ad2-6bfd290c28ce', 'd58cfb85-fbec-46c4-b2ae-b9b87b9c8d70'], writers_names=['Rick Berman', 'Michael Piller', 'Jeri Taylor'], writers_ids=['88a99b4d-4d06-4754-b06c-93217cf53244', 'd67afc96-b9ed-4c91-9507-ffc2018c58d7', 'e3a8bf89-10a9-404a-8cd8-ea249c0a654e'], directors_names=[], directors_ids=[], description="The Federation starship USS Voyager, chasing a band of Maquis rebels, enters the dangerous space nebula known as the Badlands. Both ships are transported by a distant space probe to the Delta Quadrant, 75,000 light-years from Federation space. Voyager's crew and the Maquis form an uneasy truce to rescue crewmen of both ships, kidnapped by the probe's builder, the powerful, dying Caretaker. The Maquis ship is destroyed in a battle with the warlike Kazons. To prevent a Kazon aggression against a helpless world, Voyager destroys the space probe. Without the probe, it will take 75 years for Voyager to travel back to Federation space. With the differences between them rendered meaningless by time and distance, The Federation and Maquis crews unite aboard Voyager. Together, they embark on their new mission: to boldly go - home.")]
[2023-11-03T13:28:09.919+0000] {movie_pg_es.py:119} INFO - Processing 2 movie:
[2023-11-03T13:28:09.920+0000] {movie_pg_es.py:126} INFO - [{}, {}]
[2023-11-03T13:28:09.927+0000] {_transport.py:336} INFO - PUT http://movies_es_db:9200/_bulk [status:400 duration:0.005s]
[2023-11-03T13:28:09.927+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/movie_pg_es.py", line 127, in write_to_es
    helpers.bulk(es_conn, actions)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 436, in streaming_bulk
    for data, (ok, info) in zip(
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 291, in _process_bulk_chunk_error
    raise error
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/helpers/actions.py", line 339, in _process_bulk_chunk
    resp = client.bulk(*args, operations=bulk_actions, **kwargs)  # type: ignore[arg-type]
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
    return api(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/__init__.py", line 704, in bulk
    return self.perform_request(  # type: ignore[return-value]
  File "/home/airflow/.local/lib/python3.8/site-packages/elasticsearch/_sync/client/_base.py", line 320, in perform_request
    raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
elasticsearch.BadRequestError: BadRequestError(400, 'action_request_validation_exception', 'Validation Failed: 1: index is missing;2: index is missing;')
[2023-11-03T13:28:09.990+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=movies-etl-dag, task_id=write_to_es, execution_date=20231103T132655, start_date=20231103T132809, end_date=20231103T132809
[2023-11-03T13:28:10.024+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 115 for task write_to_es (BadRequestError(400, 'action_request_validation_exception', 'Validation Failed: 1: index is missing;2: index is missing;'); 2949)
[2023-11-03T13:28:10.053+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-03T13:28:10.133+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
