[2023-11-03T11:08:21.480+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: movies-etl-dag.get_updated_movies_ids manual__2023-11-03T11:08:18.571209+00:00 [queued]>
[2023-11-03T11:08:21.491+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: movies-etl-dag.get_updated_movies_ids manual__2023-11-03T11:08:18.571209+00:00 [queued]>
[2023-11-03T11:08:21.492+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-11-03T11:08:21.510+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): get_updated_movies_ids> on 2023-11-03 11:08:18.571209+00:00
[2023-11-03T11:08:21.515+0000] {standard_task_runner.py:57} INFO - Started process 721 to run task
[2023-11-03T11:08:21.520+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'movies-etl-dag', 'get_updated_movies_ids', 'manual__2023-11-03T11:08:18.571209+00:00', '--job-id', '62', '--raw', '--subdir', 'DAGS_FOLDER/movie_pg_es.py', '--cfg-path', '/tmp/tmpyvwo30l_']
[2023-11-03T11:08:21.523+0000] {standard_task_runner.py:85} INFO - Job 62: Subtask get_updated_movies_ids
[2023-11-03T11:08:21.704+0000] {task_command.py:415} INFO - Running <TaskInstance: movies-etl-dag.get_updated_movies_ids manual__2023-11-03T11:08:18.571209+00:00 [running]> on host e468bf2dfd15
[2023-11-03T11:08:21.967+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='movies-etl-dag' AIRFLOW_CTX_TASK_ID='get_updated_movies_ids' AIRFLOW_CTX_EXECUTION_DATE='2023-11-03T11:08:18.571209+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-03T11:08:18.571209+00:00'
[2023-11-03T11:08:22.010+0000] {base.py:73} INFO - Using connection ID 'movies_db_id' for task execution.
[2023-11-03T11:08:22.119+0000] {movie_pg_es.py:54} INFO - Movies updated state: 2021-06-16 20:14:09.222623+00:00
[2023-11-03T11:08:22.123+0000] {movie_pg_es.py:57} INFO - [{'id': '57beb3fd-b1c9-4f8a-9c06-2da13f95251c', 'updated_at': datetime.datetime(2021, 6, 16, 20, 14, 9, 222623, tzinfo=datetime.timezone.utc)}, {'id': 'b1f1e8a6-e310-47d9-a93c-6a7b192bac0e', 'updated_at': datetime.datetime(2021, 6, 16, 20, 14, 9, 222674, tzinfo=datetime.timezone.utc)}]
[2023-11-03T11:08:22.124+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/movie_pg_es.py", line 59, in get_updated_movies_ids
    ti.xcom_push(key=MOVIES_UPDATED_STATE_KEY, value=str(items[-1][-1]))
KeyError: -1
[2023-11-03T11:08:22.176+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=movies-etl-dag, task_id=get_updated_movies_ids, execution_date=20231103T110818, start_date=20231103T110821, end_date=20231103T110822
[2023-11-03T11:08:22.196+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 62 for task get_updated_movies_ids (-1; 721)
[2023-11-03T11:08:22.214+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-03T11:08:22.283+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
